// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package social

import (
	"zeal_be/api/social"
)

type ControllerV1 struct{}

func NewV1() social.ISocialV1 {
	return &ControllerV1{}
}
