// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"zeal_be/internal/dao/internal"
)

// internalUserprivilegeDao is internal type for wrapping internal DAO implements.
type internalUserprivilegeDao = *internal.UserprivilegeDao

// userprivilegeDao is the data access object for table userprivilege.
// You can define custom methods on it to extend its functionality as you wish.
type userprivilegeDao struct {
	internalUserprivilegeDao
}

var (
	// Userprivilege is globally public accessible object for table userprivilege operations.
	Userprivilege = userprivilegeDao{
		internal.NewUserprivilegeDao(),
	}
)

// Fill with you ideas below.
