// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"zeal_be/internal/dao/internal"
)

// internalUserdataDao is internal type for wrapping internal DAO implements.
type internalUserdataDao = *internal.UserdataDao

// userdataDao is the data access object for table userdata.
// You can define custom methods on it to extend its functionality as you wish.
type userdataDao struct {
	internalUserdataDao
}

var (
	// Userdata is globally public accessible object for table userdata operations.
	Userdata = userdataDao{
		internal.NewUserdataDao(),
	}
)

// Fill with you ideas below.
